# Generated by Django 4.2.5 on 2023-09-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0003_alter_films_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Укажите описание фильма'),
        ),
    ]
